export const ipcChannels = {
  daemonRequest: "wateray:daemon:request",
  daemonAbortPendingRequests: "wateray:daemon:abort-pending-requests",
  daemonGetTransportStatus: "wateray:daemon:get-transport-status",
  daemonPush: "wateray:daemon:push",
  windowMinimize: "wateray:window:minimize",
  windowMinimizeToTray: "wateray:window:minimize-to-tray",
  windowToggleMaximize: "wateray:window:toggle-maximize",
  windowClose: "wateray:window:close",
  windowClosePanelKeepCore: "wateray:window:close-panel-keep-core",
  windowQuitApp: "wateray:window:quit-app",
  windowQuitAll: "wateray:window:quit-all",
  windowIsMaximized: "wateray:window:is-maximized",
  windowGetAppIconDataUrl: "wateray:window:get-app-icon-data-url",
  windowMaximizedChanged: "wateray:window:maximized-changed",
  systemOpenImportFileDialog: "wateray:system:open-import-file-dialog",
  systemOpenExportSaveDialog: "wateray:system:open-export-save-dialog",
  systemReadTextFile: "wateray:system:read-text-file",
  systemWriteTextFile: "wateray:system:write-text-file",
  systemWriteTempTextFile: "wateray:system:write-temp-text-file",
  systemReadClipboardText: "wateray:system:read-clipboard-text",
  systemWriteClipboardText: "wateray:system:write-clipboard-text",
  systemReadClipboardFilePaths: "wateray:system:read-clipboard-file-paths",
  systemWriteClipboardFile: "wateray:system:write-clipboard-file",
} as const;
