// This file is auto-generated by scripts/codegen/generate_platform_contracts.py.
// Do not edit manually.
#![allow(dead_code)]

#[derive(Clone, Copy, Debug)]
pub struct RuntimePlatformContract {
    pub kind: &'static str,
    pub is_mobile: bool,
    pub supports_window_controls: bool,
    pub supports_tray: bool,
    pub supports_packaged_daemon: bool,
    pub supports_system_proxy_mode: bool,
    pub supports_local_file_access: bool,
    pub supports_in_app_updates: bool,
    pub supports_mobile_vpn_host: bool,
    pub requires_sandbox_data_root: bool,
}

pub const RUNTIME_PLATFORM_DESKTOP: RuntimePlatformContract = RuntimePlatformContract {
    kind: "desktop",
    is_mobile: false,
    supports_window_controls: true,
    supports_tray: true,
    supports_packaged_daemon: true,
    supports_system_proxy_mode: true,
    supports_local_file_access: true,
    supports_in_app_updates: true,
    supports_mobile_vpn_host: false,
    requires_sandbox_data_root: false,
};

pub const RUNTIME_PLATFORM_ANDROID: RuntimePlatformContract = RuntimePlatformContract {
    kind: "android",
    is_mobile: true,
    supports_window_controls: false,
    supports_tray: false,
    supports_packaged_daemon: false,
    supports_system_proxy_mode: false,
    supports_local_file_access: false,
    supports_in_app_updates: false,
    supports_mobile_vpn_host: true,
    requires_sandbox_data_root: true,
};

pub const RUNTIME_PLATFORM_IOS: RuntimePlatformContract = RuntimePlatformContract {
    kind: "ios",
    is_mobile: true,
    supports_window_controls: false,
    supports_tray: false,
    supports_packaged_daemon: false,
    supports_system_proxy_mode: false,
    supports_local_file_access: false,
    supports_in_app_updates: false,
    supports_mobile_vpn_host: false,
    requires_sandbox_data_root: true,
};

pub fn resolve_runtime_platform_contract(kind: &str) -> RuntimePlatformContract {
    match kind {
        "android" => RUNTIME_PLATFORM_ANDROID,
        "ios" => RUNTIME_PLATFORM_IOS,
        _ => RUNTIME_PLATFORM_DESKTOP,
    }
}

pub const MOBILE_HOST_PLUGIN_NAME: &str = "mobile-host";
pub const MOBILE_HOST_ANDROID_PLUGIN_IDENTIFIER: &str = "com.singbox.wateray.mobilehost";
pub const MOBILE_HOST_ANDROID_PLUGIN_CLASS: &str = "MobileHostPlugin";

pub const MOBILE_HOST_BOOTSTRAP_INVOKE_COMMAND: &str = "mobile_host_bootstrap";
pub const MOBILE_HOST_BOOTSTRAP_PLUGIN_COMMAND: &str = "bootstrap";
pub const MOBILE_HOST_BOOTSTRAP_PERMISSION: &str = "mobile-host:allow-bootstrap";

pub const MOBILE_HOST_GET_STATUS_INVOKE_COMMAND: &str = "mobile_host_get_status";
pub const MOBILE_HOST_GET_STATUS_PLUGIN_COMMAND: &str = "getStatus";
pub const MOBILE_HOST_GET_STATUS_PERMISSION: &str = "mobile-host:allow-getStatus";

pub const MOBILE_HOST_GET_VERSIONS_INVOKE_COMMAND: &str = "mobile_host_get_versions";
pub const MOBILE_HOST_GET_VERSIONS_PLUGIN_COMMAND: &str = "getVersions";
pub const MOBILE_HOST_GET_VERSIONS_PERMISSION: &str = "mobile-host:allow-getVersions";

pub const MOBILE_HOST_LIST_INSTALLED_APPS_INVOKE_COMMAND: &str = "mobile_host_list_installed_apps";
pub const MOBILE_HOST_LIST_INSTALLED_APPS_PLUGIN_COMMAND: &str = "listInstalledApps";
pub const MOBILE_HOST_LIST_INSTALLED_APPS_PERMISSION: &str = "mobile-host:allow-listInstalledApps";

pub const MOBILE_HOST_GET_INSTALLED_APP_ICON_INVOKE_COMMAND: &str = "mobile_host_get_installed_app_icon";
pub const MOBILE_HOST_GET_INSTALLED_APP_ICON_PLUGIN_COMMAND: &str = "getInstalledAppIcon";
pub const MOBILE_HOST_GET_INSTALLED_APP_ICON_PERMISSION: &str = "mobile-host:allow-getInstalledAppIcon";

pub const MOBILE_HOST_PREPARE_INVOKE_COMMAND: &str = "mobile_host_prepare";
pub const MOBILE_HOST_PREPARE_PLUGIN_COMMAND: &str = "prepare";
pub const MOBILE_HOST_PREPARE_PERMISSION: &str = "mobile-host:allow-prepare";

pub const MOBILE_HOST_CHECK_CONFIG_INVOKE_COMMAND: &str = "mobile_host_check_config";
pub const MOBILE_HOST_CHECK_CONFIG_PLUGIN_COMMAND: &str = "checkConfig";
pub const MOBILE_HOST_CHECK_CONFIG_PERMISSION: &str = "mobile-host:allow-checkConfig";

pub const MOBILE_HOST_START_INVOKE_COMMAND: &str = "mobile_host_start";
pub const MOBILE_HOST_START_PLUGIN_COMMAND: &str = "start";
pub const MOBILE_HOST_START_PERMISSION: &str = "mobile-host:allow-start";

pub const MOBILE_HOST_STOP_INVOKE_COMMAND: &str = "mobile_host_stop";
pub const MOBILE_HOST_STOP_PLUGIN_COMMAND: &str = "stop";
pub const MOBILE_HOST_STOP_PERMISSION: &str = "mobile-host:allow-stop";

pub const MOBILE_HOST_CLEAR_DNS_CACHE_INVOKE_COMMAND: &str = "mobile_host_clear_dns_cache";
pub const MOBILE_HOST_CLEAR_DNS_CACHE_PLUGIN_COMMAND: &str = "clearDnsCache";
pub const MOBILE_HOST_CLEAR_DNS_CACHE_PERMISSION: &str = "mobile-host:allow-clearDnsCache";

pub const MOBILE_HOST_PROBE_INVOKE_COMMAND: &str = "mobile_host_probe";
pub const MOBILE_HOST_PROBE_PLUGIN_COMMAND: &str = "probe";
pub const MOBILE_HOST_PROBE_PERMISSION: &str = "mobile-host:allow-probe";

pub const MOBILE_HOST_PROBE_START_INVOKE_COMMAND: &str = "mobile_host_probe_start";
pub const MOBILE_HOST_PROBE_START_PLUGIN_COMMAND: &str = "probeStart";
pub const MOBILE_HOST_PROBE_START_PERMISSION: &str = "mobile-host:allow-probeStart";

pub const MOBILE_HOST_PROBE_CANCEL_INVOKE_COMMAND: &str = "mobile_host_probe_cancel";
pub const MOBILE_HOST_PROBE_CANCEL_PLUGIN_COMMAND: &str = "probeCancel";
pub const MOBILE_HOST_PROBE_CANCEL_PERMISSION: &str = "mobile-host:allow-probeCancel";

pub const MOBILE_HOST_GET_TASK_QUEUE_INVOKE_COMMAND: &str = "mobile_host_get_task_queue";
pub const MOBILE_HOST_GET_TASK_QUEUE_PLUGIN_COMMAND: &str = "getTaskQueue";
pub const MOBILE_HOST_GET_TASK_QUEUE_PERMISSION: &str = "mobile-host:allow-getTaskQueue";

pub const MOBILE_HOST_DNS_HEALTH_INVOKE_COMMAND: &str = "mobile_host_dns_health";
pub const MOBILE_HOST_DNS_HEALTH_PLUGIN_COMMAND: &str = "dnsHealth";
pub const MOBILE_HOST_DNS_HEALTH_PERMISSION: &str = "mobile-host:allow-dnsHealth";

pub const MOBILE_HOST_SWITCH_SELECTORS_INVOKE_COMMAND: &str = "mobile_host_switch_selectors";
pub const MOBILE_HOST_SWITCH_SELECTORS_PLUGIN_COMMAND: &str = "switchSelectors";
pub const MOBILE_HOST_SWITCH_SELECTORS_PERMISSION: &str = "mobile-host:allow-switchSelectors";

pub const MOBILE_HOST_PLUGIN_COMMANDS: &[&str] = &["bootstrap", "getStatus", "getVersions", "listInstalledApps", "getInstalledAppIcon", "prepare", "checkConfig", "start", "stop", "clearDnsCache", "probe", "probeStart", "probeCancel", "getTaskQueue", "dnsHealth", "switchSelectors"];
pub const MOBILE_HOST_PERMISSIONS: &[&str] = &["mobile-host:allow-bootstrap", "mobile-host:allow-getStatus", "mobile-host:allow-getVersions", "mobile-host:allow-listInstalledApps", "mobile-host:allow-getInstalledAppIcon", "mobile-host:allow-prepare", "mobile-host:allow-checkConfig", "mobile-host:allow-start", "mobile-host:allow-stop", "mobile-host:allow-clearDnsCache", "mobile-host:allow-probe", "mobile-host:allow-probeStart", "mobile-host:allow-probeCancel", "mobile-host:allow-getTaskQueue", "mobile-host:allow-dnsHealth", "mobile-host:allow-switchSelectors"];
