// This file is auto-generated by scripts/codegen/generate_platform_contracts.py.
// Do not edit manually.

export const runtimeAppTargets = ["desktop", "mobile"] as const;
export type RuntimeAppTarget = (typeof runtimeAppTargets)[number];

export type RuntimePlatformContract = {
  kind: "desktop" | "android" | "ios";
  isMobile: boolean;
  supportsWindowControls: boolean;
  supportsTray: boolean;
  supportsPackagedDaemon: boolean;
  supportsSystemProxyMode: boolean;
  supportsLocalFileAccess: boolean;
  supportsInAppUpdates: boolean;
  supportsMobileVpnHost: boolean;
  requiresSandboxDataRoot: boolean;
};

export const runtimePlatformContracts = {
  desktop: {
    kind: "desktop",
    isMobile: false,
    supportsWindowControls: true,
    supportsTray: true,
    supportsPackagedDaemon: true,
    supportsSystemProxyMode: true,
    supportsLocalFileAccess: true,
    supportsInAppUpdates: true,
    supportsMobileVpnHost: false,
    requiresSandboxDataRoot: false,
  },
  android: {
    kind: "android",
    isMobile: true,
    supportsWindowControls: false,
    supportsTray: false,
    supportsPackagedDaemon: false,
    supportsSystemProxyMode: false,
    supportsLocalFileAccess: false,
    supportsInAppUpdates: false,
    supportsMobileVpnHost: true,
    requiresSandboxDataRoot: true,
  },
  ios: {
    kind: "ios",
    isMobile: true,
    supportsWindowControls: false,
    supportsTray: false,
    supportsPackagedDaemon: false,
    supportsSystemProxyMode: false,
    supportsLocalFileAccess: false,
    supportsInAppUpdates: false,
    supportsMobileVpnHost: false,
    requiresSandboxDataRoot: true,
  },
} as const satisfies Record<string, RuntimePlatformContract>;

export type RuntimePlatformContractKind = keyof typeof runtimePlatformContracts;

export function resolveRuntimePlatformContract(kind: string): RuntimePlatformContract {
  switch (kind) {
    case "android":
      return runtimePlatformContracts.android;
    case "ios":
      return runtimePlatformContracts.ios;
    default:
      return runtimePlatformContracts.desktop;
  }
}

export const mobileHostContract = {
  pluginName: "mobile-host",
  androidPluginIdentifier: "com.wateray.desktop.mobilehost",
  androidPluginClass: "MobileHostPlugin",
  commands: {
    bootstrap: {
      invokeCommand: "mobile_host_bootstrap",
      pluginCommand: "bootstrap",
      permission: "mobile-host:allow-bootstrap",
    },
    getStatus: {
      invokeCommand: "mobile_host_get_status",
      pluginCommand: "getStatus",
      permission: "mobile-host:allow-getStatus",
    },
    getVersions: {
      invokeCommand: "mobile_host_get_versions",
      pluginCommand: "getVersions",
      permission: "mobile-host:allow-getVersions",
    },
    prepare: {
      invokeCommand: "mobile_host_prepare",
      pluginCommand: "prepare",
      permission: "mobile-host:allow-prepare",
    },
    checkConfig: {
      invokeCommand: "mobile_host_check_config",
      pluginCommand: "checkConfig",
      permission: "mobile-host:allow-checkConfig",
    },
    start: {
      invokeCommand: "mobile_host_start",
      pluginCommand: "start",
      permission: "mobile-host:allow-start",
    },
    stop: {
      invokeCommand: "mobile_host_stop",
      pluginCommand: "stop",
      permission: "mobile-host:allow-stop",
    },
    clearDnsCache: {
      invokeCommand: "mobile_host_clear_dns_cache",
      pluginCommand: "clearDnsCache",
      permission: "mobile-host:allow-clearDnsCache",
    },
    probe: {
      invokeCommand: "mobile_host_probe",
      pluginCommand: "probe",
      permission: "mobile-host:allow-probe",
    },
    probeStart: {
      invokeCommand: "mobile_host_probe_start",
      pluginCommand: "probeStart",
      permission: "mobile-host:allow-probeStart",
    },
    probeCancel: {
      invokeCommand: "mobile_host_probe_cancel",
      pluginCommand: "probeCancel",
      permission: "mobile-host:allow-probeCancel",
    },
    getTaskQueue: {
      invokeCommand: "mobile_host_get_task_queue",
      pluginCommand: "getTaskQueue",
      permission: "mobile-host:allow-getTaskQueue",
    },
    dnsHealth: {
      invokeCommand: "mobile_host_dns_health",
      pluginCommand: "dnsHealth",
      permission: "mobile-host:allow-dnsHealth",
    },
    switchSelectors: {
      invokeCommand: "mobile_host_switch_selectors",
      pluginCommand: "switchSelectors",
      permission: "mobile-host:allow-switchSelectors",
    },
  },
} as const;

export type MobileHostCommandKey = keyof typeof mobileHostContract.commands;
