// This file is auto-generated by scripts/build/common/version_sync.py.
// Do not edit manually.

export const bundledWaterayVersion = "1.6.0" as const;
export const bundledSingBoxVersion = "1.12.25" as const;
