// This file is auto-generated by scripts/build/common/version_sync.py.
// Do not edit manually.

export const bundledWaterayVersion = "1.5.0" as const;
export const bundledSingBoxVersion = "1.13.2" as const;
