// This file is auto-generated by scripts/codegen/generate_platform_contracts.py.
// Do not edit manually.

pub const MOBILE_HOST_PLUGIN_NAME: &str = "mobile-host";
pub const MOBILE_HOST_PLUGIN_COMMANDS: &[&str] = &["bootstrap", "getStatus", "getVersions", "prepare", "checkConfig", "start", "stop", "clearDnsCache", "probe", "probeStart", "probeCancel", "getTaskQueue", "dnsHealth", "switchSelectors"];
